name: TankPlugin
main: com.flouz1.tankplugin.TankPlugin
version: 1.0.0
api-version: 1.16
author: Flouz1
commands:
  flouz1:
    description: Управление экипировкой танка и гаджетами LuckyDayz.
    usage: |-
      /flouz1 com tank <helmet|chestplate|leggings|boots>
      /flouz1 com luckydayz <machete|medkit|rpd|remington|helicopter>
      /flouz1 com luckydayz helicopter speed <значение>
