name: TankPlugin
main: com.flouz1.tankplugin.TankPlugin
version: 1.0.0
api-version: 1.16
author: Flouz1
commands:
  flouz1:
    description: Tank equipment and utilities command.
    usage: /<command> ...
