name: TankPlugin
main: net.flouz.tank.TankPlugin
version: ${version}
description: ${description}
api-version: '1.16'
commands:
  flouz1:
    description: Tank equipment commands
    usage: /flouz1 ...
    permission: ''
    permission-message: ''
